### ISSUE TITLE
LMDB config

### ISSUE THREAD

**Issue by julesjacobsen** [akotlar/bystro#69]
Hi Alex. Great to talk to you yesterday at the poster session. You said you could point me to some LMDB configurations which were useful for setting up the database.

Cheers,

Jules

**Comment by akotlar** [comment]
Hey Jules, great to meet you.

Yes. Here is the LMDB config in Bystro:

https://github.com/akotlar/bystro/blob/master/lib/Seq/DBManager.pm#L964

All flags combined using bitwise OR 

### Read-only work:
1) MDB_NOLOCK , MDB_RDONLY
- RDONLY uses a read-only lock on transactions. http://www.lmdb.tech/doc/group__mdb__env.html#gac4c41c0ae044127b2fc80420c323cac6

- NOLOCK : disable the lock

When dealing with very sparse data:
MDB_NORDAHEAD: Disable system's read ahead buffer (http://www.lmdb.tech/doc/group__mdb__env.html#ga0fcdaf42f0c45749a2dff11ee322303f)

### Write/read


### General
MDB_INTEGERKEY: Use unsigned int or size_t -sized integer keys. This substantially improves performance, reduces space overhead per record (fixed size, 4 bytes on most linux systems).

ReadMode(1) (https://github.com/akotlar/bystro/blob/master/lib/Seq/DBManager.pm#L1003). Enable return of pointer from memory, rather than a copy of the value at that address. Most libraries appear to have something like this. Obviously has some danger of segfault if modifying a returned pointer (these pointers are expected to be read-only, unless WRITEMAP is enabled).

**Comment by akotlar** [comment]
Hope that helps

**Comment by akotlar** [comment]
@julesjacobsen Does this address your needs?

I also wanted to share https://mykmelez.github.io/kvbench/criterion/report/ . Some performance comparisons to LevelDB, and [Mozilla's evaluation](https://mozilla.github.io/firefox-browser-architecture/text/0017-lmdb-vs-leveldb.html) in deciding on a db backend for Firefox.

@chbe-helix max be interested as well

**Comment by julesjacobsen** [comment]
Thanks @akotlar, that's really useful. So you're using a database per chromosome and then using the position as the integer-based key? The value is a json object which maps the ref and alt alleles to whatever values?

**Comment by akotlar** [comment]
@julesjacobsen 

> So you're using a database per chromosome and then using the position as the integer-based key?

Yep. There's a database per chromosome using integer positions. The data stored at each integer key is a single multidimensional array, that you can think of as the result of a multi-table join over all tracks (data sources), those tracks' features, and any overlaps of those features (some tracks may have multiple values, and multiple records can overlap at a single chr/position, for instance refseq or Ensembl data).

We also build databases for other kinds of data, which are not necessarily keyed on integer, and which uses hash tables to store values. This includes "metadata" databases that track the track and feature mappings to their integer indices in the main database's array-based values, and data that isn't performance critical or fits better as a hash: this is seen in the case of RefSeq data: for each position in the genome, I store indices to all transcripts that overlap that position, and at runtime I look up the relevant data in the RefSeq database (or Ensembl, or whatever .bed-like file the user supplies).

**Comment by julesjacobsen** [comment]
I tried a quick implementation replicating what we currently do using [MVStore](http://www.h2database.com/html/mvstore.html) and unfortunately it's not going to work easily as a drop-in replacement due to the fixed key size and the speed of transactions when writing. Currently its 5-6x slower than MVStore which is very simple to use. This might be optimisable, but at least for the time being this isn't a high priority.

**Comment by akotlar** [comment]
I am surprised by the speed of insertion. Have you tried to use the MDB_NOSYNC flag and manually calling fsync?

**Comment by akotlar** [comment]
As a followup, https://github.com/lmdbjava/lmdbjava suggests there is some configuration issue if you're noticing slower-than-MVStore writes. 

Writes with both string and integer keys appear 2x faster than MVStore: https://github.com/lmdbjava/benchmarks/blob/master/results/20160710/README.md

**Comment by julesjacobsen** [comment]
Hmm, I'll take a closer look at the benchmark code. I re-tried using MDB_NOSYNC and MDB_WRITEMAP and this certainly speeds things up, but its still slightly slower than the MVStore. I'm not using a cursor to insert, so this is one difference worth looking into.

There are still two outstanding issues - changing the default key size and the ability to specify the database name, any ideas for that?

**Comment by akotlar** [comment]
> MDB_NOSYNC and MDB_WRITEMAP and this certainly speeds things up

I would also say that in my hands, MDB_WRITEMAP provides a much less dramatic speedup than MDB_NOSYNC.

> I'm not using a cursor to insert, so this is one difference worth looking into.

You definitely do not want to use 1 transaction commit per write. Using a cursor, or a single transaction for multiple inserts is the right way to go. Batch commits in something like a 100-1000 inserts for 1 commit. 

I would also take a look at one of the benchmark [samples](https://github.com/lmdbjava/benchmarks/blob/master/src/main/java/org/lmdbjava/bench/LmdbLwjgl.java).

If you're doing a sequential insert, use a cursor. Here is how the bench authors do it (https://github.com/lmdbjava/benchmarks/blob/master/src/main/java/org/lmdbjava/bench/LmdbLwjgl.java#L260). They use 1 long-lived transaction

> default key size

Just don't use MDB_INTEGERKEY. The default is to allow variable-length keys.

> Database name. 

For LMDB "environment" means "database", and "named database" means "table"

You *always* need to supply a database name, because you need to provide a path to the "environment" in which the LMDB db files live (this is a folder). In this folder will be 2 files. The database data file, and a .lock file.

So create a folder "my_db". Set this as the environment path. That's your database name.

If you mean having multiple LMDB databases at a single key, this is called "named databases", and that acts like a table. You need to set a maxDb parameter when opening the environment. Here is python documentation on that: https://lmdb.readthedocs.io/en/release/#named-databases. Here is LMDB C documentation on this feature:

"""
Once a transaction has been created, a database can be opened within it using mdb_dbi_open(). If only one database will ever be used in the environment, a NULL can be passed as the database name. For named databases, the MDB_CREATE flag must be used to create the database if it doesn't already exist. Also, mdb_env_set_maxdbs() must be called after mdb_env_create() and before mdb_env_open() to set the maximum number of named databases you want to support.
"""

Here is how I handle this in a related project: https://github.com/akotlar/GenPro/blob/genpro-lmdb/lib/GenPro/DBManager.pm#L534
  * when you go to openDb, pass in the table name. You must have MDB_CREATE flag set for this to work.
